### ISSUE TITLE
Code updates Thursday 28/1

### ISSUE THREAD

**Issue by ZiggyHowland** [ZiggyHowland/JavaDev#1]
@andyolsen I test using GIT ony to communicate code with you, but let me know in case this is inconvenient. I fully understand your need to align your way of interaction with all of us in a propriate (and maybe similar) way. Until I do not hear anything I continue using GIT. 

Updates to my code is pushed to this repo, and I've included a few questions as well. You decide if it is convenient to answer them in a lesson or write back.

**Comment by andyolsen** [comment]
See my embedded comments and remarks, indicated by ANDY

**Comment by Salimzo** [comment]
Too late to the party. Thanks for the invite.
